#!/bin/bash
# ============================================================
# DEEPFAKE DETECTION SYSTEM - FULL REBUILD SCRIPT
# ============================================================
# Run on GPU server: Ubuntu 22.04, CUDA 11.8+, 8GB+ VRAM
# Execute from: deepfake_detection_py/ directory
#
# REQUIRED WEIGHT FILES (Generated by this script):
#   1. xception_spatial.pth         -> Xception face classifier (FF++)
#   2. image_detector_v4_realworld.pth -> EfficientNet-B4 texture guard
#   3. image_detector_v5_frequency.pth -> EfficientNet-B0 frequency guard
#   4. image_frequency_model.pth    -> ResNet-18 frequency (video pipeline)
#   5. video_temporal_model.pth     -> TimeSformer temporal motion
# ============================================================

set -e  # Exit on any error

echo "============================================"
echo " DEEPFAKE DETECTION SYSTEM REBUILD"
echo " $(date)"
echo "============================================"

# ---- STEP 0: SYSTEM DEPENDENCIES ----
echo ""
echo "[STEP 0] Installing system dependencies..."
sudo apt update && sudo apt install -y ffmpeg
echo "[OK] ffmpeg installed."

# ---- STEP 1: PYTHON ENVIRONMENT ----
echo ""
echo "[STEP 1] Setting up Python environment..."
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip

# PyTorch with CUDA 11.8
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

# All other dependencies
pip install -r requirements.txt

echo "[OK] Python environment ready."
echo "[*] PyTorch CUDA available: $(python3 -c 'import torch; print(torch.cuda.is_available())')"

# ---- STEP 2: DATASET PREPARATION ----
echo ""
echo "============================================"
echo "[STEP 2] DATASET PREPARATION"
echo "============================================"
echo ""
echo "Before proceeding, ensure the following data is in place:"
echo ""
echo "  A) FaceForensics++ (c40 compression):"
echo "     FaceForensics/"
echo "       original_sequences/youtube/c40/videos/   (~300 real videos)"
echo "       manipulated_sequences/Deepfakes/c40/videos/"
echo "       manipulated_sequences/Face2Face/c40/videos/"
echo "       manipulated_sequences/FaceSwap/c40/videos/"
echo ""
echo "  B) Real-World Images (for EfficientNet ensemble):"
echo "     datasets/image_realworld/"
echo "       real/   (~6,000 images: CelebA-HQ, FFHQ)"
echo "       fake/   (~8,000 images: StyleGAN, SDXL, DiffusionDB)"
echo ""
read -p "Press ENTER when all datasets are ready..."

# ---- STEP 2a: Extract Face Crops from FF++ ----
echo ""
echo "[STEP 2a] Extracting face crops from FF++ videos..."
echo "          Target: ~36,000 face crops (300 videos x 4 categories x 30 frames)"
python3 preprocess.py
echo "[OK] Face crops saved to datasets/processed_faces/"

# ---- STEP 2b: Extract 16-Frame Video Clips ----
echo ""
echo "[STEP 2b] Extracting 16-frame temporal clips..."
echo "          Target: ~21,000 clips for TimeSformer"
python3 extract_video_clips_v2.py
echo "[OK] Video clips saved to datasets/video_clips_16f/"

# ---- STEP 3: TRAIN ALL MODELS ----
echo ""
echo "============================================"
echo "[STEP 3] MODEL TRAINING (5 models)"
echo "============================================"

# 3a: Xception Spatial (Lead model - 40% weight in fusion)
echo ""
echo "[STEP 3a] Training Xception Spatial Model..."
echo "          Data: ~36,000 FF++ face crops"
echo "          Target Val Acc: ~94%"
python3 train_xception_spatial.py
echo "[OK] xception_spatial.pth generated."

# 3b: EfficientNet-B4 Texture Guard (30% weight in fusion)
echo ""
echo "[STEP 3b] Training EfficientNet-B4 Texture Guard..."
echo "          Data: ~14,000 real-world images"
echo "          Target Val Acc: ~89.5%"
python3 train_efficientnet_texture.py
echo "[OK] image_detector_v4_realworld.pth generated."

# 3c: EfficientNet-B0 Frequency Guard for image pipeline (20% weight)
echo ""
echo "[STEP 3c] Training EfficientNet-B0 Frequency Guard..."
echo "          Data: ~14,000 noise residuals"
echo "          Target Val Acc: ~91%"
python3 train_efficientnet_frequency.py
echo "[OK] image_detector_v5_frequency.pth generated."

# 3d: ResNet-18 Frequency for video pipeline
echo ""
echo "[STEP 3d] Training ResNet-18 Frequency Model (video pipeline)..."
python3 train_image_frequency.py
echo "[OK] image_frequency_model.pth generated."

# 3e: TimeSformer Temporal (10% weight in fusion)
echo ""
echo "[STEP 3e] Training TimeSformer Temporal Model..."
echo "          Data: ~21,000 16-frame clips"
echo "          Target Val Acc: ~92.4%"
python3 train_video_timesformer.py
echo "[OK] video_temporal_model.pth generated."

# ---- STEP 4: VERIFY ALL WEIGHTS ----
echo ""
echo "============================================"
echo "[STEP 4] WEIGHT VERIFICATION"
echo "============================================"

ALL_GOOD=true
for f in xception_spatial.pth image_detector_v4_realworld.pth image_detector_v5_frequency.pth image_frequency_model.pth video_temporal_model.pth; do
    if [ -f "$f" ]; then
        SIZE=$(du -h "$f" | cut -f1)
        echo "  [OK] $f ($SIZE)"
    else
        echo "  [FAIL] MISSING: $f"
        ALL_GOOD=false
    fi
done

if [ "$ALL_GOOD" = false ]; then
    echo ""
    echo "[!] Some weights are missing. Check training logs above for errors."
    exit 1
fi

# ---- STEP 5: SMOKE TEST ----
echo ""
echo "[STEP 5] Running smoke test..."
python3 -c "
import torch
from model import get_model, DeepfakeTimeSformer
from torchvision import models
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

# Test Xception
m = get_model('xception', pretrained=False)
m.load_state_dict(torch.load('xception_spatial.pth', map_location=device))
print('[OK] Xception loaded')

# Test B4
m = models.efficientnet_b4(weights=None)
m.classifier[1] = nn.Sequential(nn.Dropout(0.3), nn.Linear(m.classifier[1].in_features, 1))
m.load_state_dict(torch.load('image_detector_v4_realworld.pth', map_location=device))
print('[OK] EfficientNet-B4 loaded')

# Test B0
m = models.efficientnet_b0(weights=None)
m.classifier[1] = nn.Sequential(nn.Dropout(0.3), nn.Linear(m.classifier[1].in_features, 1))
m.load_state_dict(torch.load('image_detector_v5_frequency.pth', map_location=device))
print('[OK] EfficientNet-B0 loaded')

# Test TimeSformer
m = DeepfakeTimeSformer(num_frames=16)
m.load_state_dict(torch.load('video_temporal_model.pth', map_location=device))
print('[OK] TimeSformer loaded')

print('[PASS] All models load successfully!')
"

# ---- STEP 6: DEPLOY ----
echo ""
echo "============================================"
echo "[STEP 6] DEPLOYMENT"
echo "============================================"
echo ""
echo "All models trained and verified. To deploy:"
echo ""
echo "  # Install pm2 if not already installed:"
echo "  npm install -g pm2"
echo ""
echo "  # Start the service:"
echo "  pm2 start 'uvicorn main:app --host 0.0.0.0 --port 8001' --name deepfake-monitor"
echo ""
echo "  # Set in your backend .env:"
echo "  DEEPFAKE_ML_URL=http://<server-ip>:8001"
echo ""
echo "============================================"
echo " REBUILD COMPLETE - $(date)"
echo "============================================"
